### ISSUE TITLE
How to secure pages

### ISSUE THREAD

**Issue by traustitj** [PiranhaCMS/piranha.core.docs#20]
I am trying to add a user page that requires authentication. So I added a user with rights to view pages, and nothing else, but he isn't able to login, at all. You are just redirected to login page again, no error.
As far as I have tested, you have to be administrator to login.

The user should be able to login, and ONLY see his own information, something I will make.

Is this possible?

**Comment by tidyui** [comment]
I moved this issue to the docs repo as well

**Comment by traustitj** [comment]
Hi.
Thank you so much.
I made this repo, https://github.com/traustitj/piranhalogin.git

Not Sure what I am doing wrong here.

**Comment by tidyui** [comment]
I think I missed out one thing for MVC. This baseclass when using Razor Pages catches the exception thrown by model loader and returns unauthorized:

https://github.com/PiranhaCMS/piranha.core/blob/master/core/Piranha.AspNetCore/Models/SinglePost.cs#L72

You need to add the same behavior by yourself in your controller actions in CmsController, otherwise you will just get an exception and not a 401.

Regards

**Comment by traustitj** [comment]
Ahh, thank you. You really helped me a great deal.

**Comment by traustitj** [comment]
Works like a charm.
